services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    container_name: sqlserver
    environment:
      SA_PASSWORD: "kinit@2603"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "kinit@2603", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10

  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    platform: linux/amd64
    depends_on:
      - sqlserver
    volumes:
      - ../../data/sqlserver:/scripts
    entrypoint: /bin/bash -c "sleep 20 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P kinit@2603 -d master -i /scripts/init.sql"

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ../../data/cassandra:/docker-entrypoint-initdb.d

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
      - "9094:9094"
    environment:
      # KRaft mode configs
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9093,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_data:/bitnami/kafka

  dotnetapp:
    build: ../../
    ports:
      - "5136:5136"
    environment:
        - ASPNETCORE_URLS=http://+:5136
    depends_on:
      - sqlserver
      - cassandra
      - kafka

  frontend:
    build: ../../frontend/order-portal
    ports:
      - "4200:80"
    depends_on:
      - dotnetapp

volumes:
  kafka_data:
